### ISSUE TITLE
Port of Draconix's EyeZoomMacro for Julti?

### ISSUE THREAD

**Issue by epictechie135** [DuncanRuns/Jingle#1]
As a former Julti user, I'm really enjoying the benefits of Jingle being overall simpler and lighter on my PC. However, I would say one downside I miss about Julti is Draconix's specific EyeZoomMacro. While there is an alternative that exists on the Jingle default scripts, I still would like the added advantage of the second resolution and the subpixel overlay. The overlay is extremely useful for new runners such as myself, that don't yet have the skill to perfectly align the crosshair by the subpixels. This way if I'm only three or four subpixels off, it's easy for me to see at a glance and quickly input the angle corrections in NinjaBrain. 

Proposed solutions:
1. The easiest, and by far the simplest would be to ask Draconix permission to use their code and re-format it to run with Jingle. Thus saving time, and also preserving parity between the two versions. 
2. The second and most difficult would be to re-write the the script from scratch alongwith the second resolution and the overlay image,

**Comment by DuncanRuns** [comment]
See Jingle's OBS tab for a measuring projector.

I don't plan on implementing a measuring projector directly into Jingle, it has too many disadvantages compared to an OBS projector

**Comment by DuncanRuns** [comment]
Added in 9ea122255db3600679a7d1a5b3e2bb46846a99f2

**Comment by EpicTechie** [comment]
Thank you so much for taking my issue into consideration! I love Jingle and now love it even more because of this. Huge props to you as a programmer and moderator 🫶
